### ISSUE TITLE
Remove need for rq-scheduler

### ISSUE THREAD

**Issue by cunla** [cunla/django-rqscheduler#15]
**Is your feature request related to a problem? Please describe.**
Remove need for rq-scheduler.
django-rq has internal scheduler since version 1.2.0.

**Comment by gabriels1234** [comment]
Hi!
Why wontfix?
It would save the need for another instance running to do the scheduling...

**Comment by cunla** [comment]
Well, it is not as simple when you have multiple workers... better to have one scheduler

**Comment by gabriels1234** [comment]
@cunla Thanks for the reply. Apparently workers coordinate to perform this job well.

In practice, I came about this project since my scheduler wasn't working (in the old django-rq-scheduler project), I had programmatically scheduled jobs sitting there for minutes (and I think the workers where waking up and fixing it).

This is what the documentation says:


```
Only a single scheduler can run for a specific queue at any one time.
If you run multiple workers with scheduler enabled, only one scheduler will
 be actively working for a given queue.

Active schedulers are responsible for enqueueing scheduled jobs.
Active schedulers will check for scheduled jobs once every second.

Idle schedulers will periodically (every 15 minutes) check whether 
the queues they’re responsible for have active schedulers.
 If they don’t, one of the idle schedulers will start working. 
This way, if a worker with active scheduler dies, the scheduling work will be picked up by other workers with the scheduling component enabled.
```
I know they also claim that "If you need a battle tested version of RQ job scheduling, please take a look at https://github.com/rq/rq-scheduler instead." But I feel this has less moving parts, and it costs less...

Is it possible to make it so it doesn't rely on rq-scheduler?
Thanks!
