### ISSUE TITLE
2023.1+ "cron" explanation + re-scheduling of cron jobs not working

### ISSUE THREAD

**Issue by gabriels1234** [cunla/django-rqscheduler#75]
HI @cunla ! 
I'm successfully deploying 2023.1 , and as far as I've seen, it replaces the rq-scheduler's  "cron()" with a smart way of scheduling the next run.

I wanted to make sure about a few things:

1) what happens if I manually remove the crons that are "scheduled"? is there a recovery mechanism? (this is  not an issue)

2) is there a job de-duplication check that, for example, if the job is in the "scheduled" registry, going to the Cron section and clicking on "run now" will have no effect, apparently.

3) what If I go to the scheduled registry for a job and click "Enqueue". then it will run, but stay in the scheduled registry (at least for a while) as "finished". what about the *next* run, do I have to disable the cron and re-enable to have the "next" run?

Perhaps I could help with some documentation/readme after I have mastered how it works?

**Comment by gabriels1234** [comment]
I've found this:
```
    def run_job_now(self, request, queryset):
        job_names = []
        for obj in queryset:
            kwargs = obj.schedule_kwargs()
            obj.get_queue2().enqueue_at(
                utc(now()),
                obj.callable_func(),
                *obj.parse_args(),
                **kwargs
            )
            job_names.append(obj.name)
        self.message_user(request, "The following jobs have been run: %s" % (', '.join(job_names),))
```

Perhaps this scheduling is conflicting with the cron scheduling?
perhaps `obj.get_queue2().enqueue()` should be called instead?

**Comment by gabriels1234** [comment]
Also found:

```

    def reschedule_jobs(jobs):
        for job in jobs:
            if job.is_scheduled() is False:
                job.save()
```
Perhaps this check needs to consider that it's better to schedule it if the time is earlier than the one scheduled.

**Comment by gabriels1234** [comment]
<img width="217" alt="image" src="https://user-images.githubusercontent.com/96071233/212131088-6ea5aff9-3535-41f7-9b25-337fe7db1424.png">
What does it mean it's not scheduled (it's enabled)? will this be self-healed?

EDIT: As far as my tests are going, the is_scheduled turns to false and there's no "second reschedule" (after the first run of the cron job finishes). (the rescheduling happens on the ready() method, but not sure how often that happens).
One idea would be to make the reschedule be added as the at_success and at_failure arguments of the job.
Let me know!

**Comment by gabriels1234** [comment]
I made a hotfix branch that seems to work. can do a PR for it.

**Comment by gabriels1234** [comment]
@cunla would put my PR for your consideration.

**Comment by cunla** [comment]
Hi,

A lot to unpack here :)

Most important: PRs are always welcome! and they don't have to be code changes. You can also update the README. 
Regarding documentation: I started following [this tutorial](https://docs.readthedocs.io/en/stable/tutorial/) and also registered to readthedocs so it will build https://django-rq-scheduler.readthedocs.io/en/latest/, but I haven't gotten around to it. Your support is appreciated.


> what happens if I manually remove the crons that are "scheduled"? is there a recovery mechanism? (this is not an issue)

Also related to enabled but not scheduled => I think you are on to a bug. the rq scheduler is looking on scheduled_job_registry but after scheduling it once it removes it instead of keeping it for next round.

> is there a job de-duplication check that, for example, if the job is in the "scheduled" registry, going to the Cron section and clicking on "run now" will have no effect, apparently.

I think we should be careful with this. If the job is to send emails (many of the jobs I have), and scheduled to run in 5 mins, but you are running it now - it might spam users.

> what If I go to the scheduled registry for a job and click "Enqueue". then it will run, but stay in the scheduled registry (at least for a while) as "finished". what about the next run, do I have to disable the cron and re-enable to have the "next" run?

Yeah, this is a bug which your PR address! nice!
